{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seizu.secretName" . }}
  labels:
    {{- include "seizu.labels" . | nindent 4 }}
  {{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
{{- if or .Values.secrets.data.neo4jUser .Values.secrets.data.neo4jPassword .Values.secrets.data.oidcClientSecret .Values.secrets.data.reportQuerySigningSecret .Values.secrets.data.sessionTokenEncryptionKey }}
stringData:
  {{- with .Values.secrets.data.neo4jUser }}
  NEO4J_USER: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.data.neo4jPassword }}
  NEO4J_PASSWORD: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.data.oidcClientSecret }}
  OIDC_CLIENT_SECRET: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.data.reportQuerySigningSecret }}
  REPORT_QUERY_SIGNING_SECRET: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.data.sessionTokenEncryptionKey }}
  SESSION_TOKEN_ENCRYPTION_KEY: {{ . | quote }}
  {{- end }}
{{- end }}
{{- end }}
